nodeLinker: node-modules

plugins:
  - checksum: cd3f4b29fc21d0ba90e019d9ab5676869b6e573c1c390d9037c1f1f5e367026f341d5b07c5aa2c408d4db56b03eb65efa3e94aa49a01d4ba7ebfba829697fef3
    path: .yarn/plugins/@yarnpkg/plugin-interractive-filter.cjs
    spec: "https://raw.githubusercontent.com/eyolas/yarn-plugin-interractive-filter/master/bundles/%40yarnpkg/plugin-interractive-filter.js"

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.9.2.cjs
