# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lfx-v2-pcc-ui.fullname" . }}
  labels:
    {{- include "lfx-v2-pcc-ui.labels" . | nindent 4 }}
  {{- with (include "lfx-v2-pcc-ui.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lfx-v2-pcc-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "lfx-v2-pcc-ui.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "lfx-v2-pcc-ui.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "lfx-v2-pcc-ui.serviceAccountName" .) }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ include "lfx-v2-pcc-ui.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          {{- range $name, $config := .Values.environment }}
          - name: {{ $name }}
            {{- if $config.value }}
            value: {{ $config.value | quote }}
            {{- else if $config.valueFrom }}
            valueFrom:
              {{- toYaml $config.valueFrom | nindent 14 }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
