---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: License Header Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  license-header-check:
    uses: linuxfoundation/lfx-public-workflows/.github/workflows/license-header-check.yml@main
