# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT

name: Quality Checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Setup Turborepo cache
        uses: actions/cache@v4
        with:
          path: |
            .turbo
            node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/*', '!**/node_modules/**', '!**/.turbo/**') }}
          restore-keys: |
            ${{ runner.os }}-turbo-${{ hashFiles('**/yarn.lock') }}-
            ${{ runner.os }}-turbo-

      - name: Check formatting
        run: yarn format:check

      - name: Run linting
        run: yarn lint:check

      - name: Type checking
        run: yarn check-types

      - name: Build project
        run: yarn build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts-turbo
          path: |
            apps/lfx-pcc/dist/
            !apps/lfx-pcc/dist/**/*.map
          retention-days: 7

      - name: Upload Turborepo cache summary
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: turbo-cache-summary
          path: .turbo/
          retention-days: 1